### ISSUE TITLE
Make hadoop-unit available in public repo

### ISSUE THREAD

**Issue by framiere** [jetoile/hadoop-unit#2]
Poor souls behind corporate proxies would need this! :)

**Comment by jetoile** [comment]
Do you know process to publish to maven central repo?

**Comment by framiere** [comment]
Sure, you just need to follow this workflow https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by jetoile** [comment]
Bon, je switch en français... ;) tu penses que le projet vaut la peine de
faire une release dans le maven central? J'avoue que j'ai un doute quand au
peu de valeur qu'il a...
Le 24 avr. 2016 1:40 PM, "Florent Ramière" <notifications@github.com> a
écrit :

**Comment by framiere** [comment]
I clearly see value in your work. Just cut a release, publish it and see how it goes.

**Comment by jetoile** [comment]
snapshot released on https://oss.sonatype.org/#nexus-search;quick~hadoop-unit-standalone
