### ISSUE TITLE
commit files as executable

### ISSUE THREAD

**Issue by grozeille** [jetoile/hadoop-unit#77]
mathias@pc-mathias  ~/Work/tools/hadoop-unit-standalone-2.3-SNAPSHOT  bin/hadoop-unit-standalone console
Unable to locate any of the following operational binaries:
  /Users/mathias/Work/tools/hadoop-unit-standalone-2.3-SNAPSHOT/bin/./wrapper-macosx-universal-64 (Found but not executable.)
  /Users/mathias/Work/tools/hadoop-unit-standalone-2.3-SNAPSHOT/bin/./wrapper-macosx-universal-32
  /Users/mathias/Work/tools/hadoop-unit-standalone-2.3-SNAPSHOT/bin/./wrapper

**Comment by jetoile** [comment]
Hi Mathias,

Thanks for the issue. I was aware of that but I forgot to fix this...
This is fix by the commit ecfde474a4f8cbcff662caa583da8bb0b797147e
