### ISSUE TITLE
Update Spark version from 1.6 to 2.2

### ISSUE THREAD

**Issue by martmull** [jetoile/hadoop-unit#83]
Hi, 
The renault datalake updated its Spark version from 1.6 to 2.2
Do you think you can update the Spark version on hadoop unit standalone version too?
Thanks,

**Comment by jetoile** [comment]
Hello,

Hadoop Unit does not provide spark. 
If you want to use spark, you have the local mode.
Hadoop Unit just provides a pom’s helper (hadoop-unit-client-spark) with which you can use to avoid manually adding exclude section in the pom.xml.
By the way, Hadoop Unit is already using Spark 2.2.

**Comment by martmull** [comment]
Ok, thank you jetoile.
